manifest.json
This fixes #3. I've tested it on a problematic `<iframe>` on irccloud.com.
=> Add match_about_blank to fix #3

background.js
Push styles only to the main frame of a tab; let the content script pull styles into child frames, as before.
`chrome.tabs.sendMessage` can only broadcast to all frames in a tab until Chrome 41. The main frame always fires `onCommit` before any child frame, so only the main frame hears its own message from `onCommit`. It (and every child frame that's already fired `onCommit`) hears the `onCommit` message for every frame that follows, with the result that the main frame applies all the styles for every frame in the tab.
https://forum.userstyles.org/discussion/45062/stylish-for-chrome-1-3-0b1#Comment_95474
=> Only push styles to the top-level document.

popup.js
Reduce `file:///...` URLs to just `file:` to prevent "Find more styles" from leaking filesystem structure to network. Userstyles currently will redirect to https://userstyles.org/styles/browse?search_terms=file%3A
=> Sanitize `file:` URLs in "Find more styles"

apply.js, background.js
Tumblr's 'new post' buttons rewrite the current URL with `history.pushState`; they can be used with [this style](https://userstyles.org/styles/110723/test-history-pushstate-observer-tumblr) to demonstrate functionality.
Fragment identifier changes can probably be handled similarly with `onReferenceFragmentUpdated`, but I haven't a site to test against.
=> Reload styles on `history.pushState`

edit.html, edit.js
Edit: ~~removed the accelerator hotkeys for other buttons.~~
Adding localized accelerator hotkeys for other buttons would require a lot more work to no benefit, because: 1) those other controls aren't as frequently used as Ctrl-S inside a code textbox while modifying/writing a style, 2) accelerator keys focus the element so it won't be possible to continue typing without tabbing through a lot of controls.
=> Edit style: add Ctrl-S hotkey to save the style

edit.html
Now it's possible to view/edit long urls and regexps with much more comfort:
CSS `flex` properties in un-prefixed form are supported since Chrome 29.
=> Edit style: expand URL boxes to page width

popup.js
Optionally display enabled styles before disabled styles in the popup menu. Preference `localStorage['popup.enabledFirst']` controls the behavior; default is 'true'.
=> Popup: sort enabled styles first

popup.html, popup.js
Adds support for 'new style' links that resemble the page URL. Requires stylesheet support to enable it.
https://userstyles.org/styles/110560/breadcrumbs-new-style-links-stylish-for-chrome
Was https://github.com/JasonBarnabe/stylish-chrome/pull/30
=> Support "breadcrumbs" new style links

background.js, edit.js, messaging.js, popup.js, storage.js
Adds a global object `prefs`, with a list of all preferences and their default values, and methods `getPref` and `setPref` to read and write preference values. The objective is to centralize preference handling.
`getPref(key, defaultValue)` returns the user value from `localStorage` if it exists, or the default value from `prefs` if it doesn't. If the optional `defaultValue` is present, it's used instead of the default value in `prefs`. The returned value is converted to the type of the default value.
`setPref(key, value)` sets the user value in `localStorage`. If `value` is `undefined`, the user value is evicted from `localStorage`. The value is converted to a string with `JSON.stringify()` before it's stored.
Some `assert`s which exercise the object: …
=> Get and set typed preference values

popup.js
When a new tab page is active both Google Chrome and Firefox re-use it to open settings/preferences, thus it'd be logical for Stylish-Chrome to also do that.
This change actually affects only the "Manage styles" link currently, because the Edit links aren't shown on a new tab page ("Stylish can't style pages like this").
=> Re-use an active new tab page for manager/editor

edit.js, popup.js
Use `url-prefix()` instead of `url()` when creating a new style with "this URL". *in re* #42.
`url-prefix()` is used much more often than `url()` [https://github.com/JasonBarnabe/stylish-chrome/issues/42#issuecomment-76667390]. This change eliminates the step of changing the match type in almost all new styles.
=> Create new styles with `url-prefix()`

_locales/en/messages.json, edit.html, edit.js
Closes #56.
In addition to the default hotkeys like Ctrl-F, Ctrl-G and so on, the 'sublime' keymap adds Windows-standard F3, Shift-F3, Ctrl-H - find, find previous, replace and many more. Since Sublime editor is very popular for code development, we may use this keymap by default for Stylish-Chrome.
Custom hotkeys (my implementation):
| custom key | function |
|---------|-------------|
| Ctrl-G | go to line dialog |
| Alt-PgDn | next code section |
| Alt-PgUp | previous code section |
So Ctrl-G overrides _find next_. Will Mac users of Stylish Chrome complain, I wonder? I mean, all 3 of them!
| sublime key | function |
|---------|-------------|
| Alt-F2 | selectBookmarks |
| Alt-F3 | findAllUnder |
| Alt-Left | goSubwordLeft |
| Alt-Q | wrapLines |
| Alt-Right | goSubwordRight |
| Ctrl-/ | …
=> Edit style: use 'sublime' keymap, add custom keys

edit.html, edit.js
1. 514a1227e49351eb56a9a11453643a1ac0ac1c88: **Search from within code editor now searches other sections too.**
* All matches are immediately highlighted in all sections (text and scrollbar annotations)
* If the active code editor has no match in the selected direction of search, the section containing the search term will be auto-focused.
* *TO CONSIDER:* override Ctrl-F/F3 on the entire page, display a simple inputbox somewhere, and perform the search in code and applies-to definitions.
2. cd8d11b1373817ce4096d1aca2cca744707d5ba0: **Scroll the clicked section into view by minimally required amount**, thus preventing sudden jumping of only a partially hidden section into the center of the page
3. 74268d98eb679bb5e24edf3efa8e6c06398600fc: **Indicate the active code box with a darker …
=> Search all sections on find, findNext, findPrev when invoked from the editor

manage.js, popup.js, storage.js
Fixes: 6ec65ab
1. `loadPrefs` was called with string instead of boolean
2. Sense of boolean `popup.breadcrumbs.usePath` was inverted
3. `loadPrefs` wasn't passing default to `getPrefs`
4. `JSON.stringify(string)` added quotes to string
5. Preferences `manage.enabledFirst`, `observer.observeFrameContent`, `observer.observeFrameLoad` aren't used
Improvements: 0eaa356
1. An element's `change` listener can be used to initialize what it's controlling. `loadPrefs` sends a `change` event to the element after setting the element `value` but before adding its own `change`
listener. Add the element's listener before calling `loadPrefs` to receive the synthetic event.
2. `prefs.setPref` only broadcasts a notification if the value returned by `getPref` changes.
3. A user preference with the same …
=> Preferences fixes & improvements

codemirror/addon/lint/css-lint.js, edit.html, edit.js, popup.js
1. On the _Write a new style_ page also search in all code sections
2. Mostly mute CSSLint, re-enable gutter marks, hide squiggles. Closes #51. Only these are enabled:
* Parsing Errors
* Disallow empty rules
* Require use of known properties
* Require properties appropriate for display
3. Fix goto next/prev section after deleting one thereof.
4. Remember detached window position and size, closes #47
5. Retain scroll position of window & editor on click, preventing wild jumps of Chrome's scroll-on-focus.
6. Allow adding sections midway, autofocus the manually added one, thus ensuring it's entirely visible
7. Save on Ctrl-S outside code blocks too
8. Warn on losing changes to applies-to text input fields
=> Edit style: more tweaks

csslint/csslint.js, edit.js
Evaluate string token with `RegExp.exec()` instead of `eval()`. And, fixing a *second* use of `loadPrefs`.
You need permission for `eval()`; you can't [just ignore it](#51).
=> Remove `eval` from css-lint

_locales/en/messages.json, manage.html, manage.js, storage.js
Two independent filters. One allows only styles that are enabled, the other allows only styles that were written locally (that is, styles without an update URL).
=> Listing filters for 'Manage'

_locales/en/messages.json, edit.html, edit.js, storage.js
1. Add UI controls for `keyMap`, `tabSize`, `indentWithTabs`, and `lineWrapping`; `indentUnit` tracks `tabSize`.
2. Dispatch `change` events from `loadPrefs` to initialize CM options from the controls' event listener.
3. Let the CodeMirror object be arbiter for the editor instances: Move stock options from the `CM.fromTextArea` call into `CM.defaults`. Add a `CM.setOption` method, analogous to the instance method, which updates `CM.defaults` and sets the option in all instances; add a `CM.getOption` which simply returns `CM.defaults[option]`.
4. Move the new editor functions into `CM.commands` and replace the functions with commands.
The changes of #62 are incorporated here.
=> Add editor options

_locales/en/messages.json, manage.html, manage.js, popup.html, popup.js, storage.js
Styles are listed before actions by default. Actions are listed before styles if `popup.stylesFirst` is false. A control for the option is shown in "Manage" if `popup.stylesFirstUI` is true.
This option permits the Stylish popup to be consonant with OS 'File' and 'Window' menus which place variable MRU items at or near the end of the list. It allows the actions to always be in view when the toolbar button is clicked, regardless of the number of styles available in the menu. It also eliminates the annoyance of clicking an action but missing because the query results arrived and washed the action links away downstream.
=> [option] List actions before styles in the popup

edit.html, edit.js
1. Record initial value of text, select, and checkbox elements and re/set a dirty class on each when the value changes.
2. Combine the individual flags into a global dirty flag.
3. Add 'dirty' status to the document title.
=> Manage dirty flags on all inputs

_locales/ar/messages.json, _locales/cs/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fi/messages.json, _locales/fr/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/pt_BR/messages.json, _locales/ru/messages.json, _locales/sv_SE/messages.json, _locales/te/messages.json, _locales/tr/messages.json, _locales/zh/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, edit.html, edit.js
Narrow width editor:
* webkit `columns` flow bug workaround, fixup for 02e1255580107845695e127673084411960dcd4e, I couldn't keep `text-align: right` for the tabsize edit because it makes Chrome throw the number from inside of the input into the first column, but it looks even better now, probably, because of the uniform left-align.
* better alignment of tabular options: fixup 02e1255580107845695e127673084411960dcd4e
* better alignment of action buttons wrapped to 2nd line 
* drop the `Name` label to greatly improve alignment in the narrow width windows
* reorder \#basic-info as `Name________` `[x]` `Enabled` since it's only one line unlike the two-line grid in the full width editor.
Actually it would suit the full width layout too, if you don't mind:
General changes:
* remove `BR` tag …
=> Editor: webkit bug workaround; better alignment

edit.html, edit.js
~~Simply force CodeMirror instances to render entirely when the browser search is invoked using default hotkeys (not from a menu) like Ctrl-F and so on. On the first cursor activity inside a code box its internal viewport is contracted back to the default value, thus making the editor fast again. See #72.
However, to fully implement it, our internal *page-global* search should have a [simple] UI separate from CodeMirror's in order to allow searching in applies-to fields. That's why I'm offering this temporary partial solution.~~
Simply reroute the browser search to a closest CodeMirror box.
Won't work if invoked via the browser menu or a non-standard hotkey.
Closes #72
=> Editor: reroute the browser search to a closest CodeMirror box

_locales/en/messages.json, background.js, edit.js, manifest.json, popup.js, storage.js
* **Hotkeys**
* hotkey to open Manage styles
* hotkey to enable/disable all styles
No default hotkeys are assigned, to customize go to "Keyboard shortcuts" on the Extensions page
* **Toolbar button context menu** features 2 global behavior toggles:
* show-badge pref, a new i18n label was added as it must be very short to keep the menu small
* disableAll pref
=> Add Chrome shortcut keys; update all visible popups on change; add 2 prefs to toolbar button menu

edit.js
When editing an applies-to field, use its code box for search on Ctrl-F, etc. But only if there will be no scrolling to make its top visible.
=> Editor: when in applies-to, use its code box for search on Ctrl-F, etc.

apply.js
This removes momentary flashing of the original unstyled content on "Manage styles" and "Edit style" when custom styles for these pages are used.
=> Apply styles to own pages earlier to avoid flicker

background.js
This fixes Stylish in Chromodo 36 and earlier Chromium-based browsers.
P.S. didn't indent the inner block to simplify git blame retrospections.
=> Fix old Chrome error: no 'browser_action' contextMenu type

_locales/en/messages.json, edit.html, edit.js, localization.js, manage.html, manage.js, popup.html, popup.js
Closes #84
* localization is applied earlier now, before the page is rendered, thus eliminating the flicker and layout reflow when the original empty content was briefly shown
* HTML-attributes are used:
* `i18n-text="stringID"` for node.textContent
* `i18n-html="stringID"` for node.innerHTML
* `i18n-anyAttribute="stringID"` to add anyAttribute with a localized value.<br>
<sup>Earlier I suggested attr="i18n:stringID" form but decided against it in favor of uniformity.</sup>
* HTML templates in js files are now created via `tHTML`:
* it creates the outer node<br>
so instead of `var template = document.createElement("div"); template.innerHTML = "stuff" + t("ID")`<br>
now it's just `var template = tHTML('<div>stuff with i18n-attributes</div>');`<br>
or even `var template = tHTML('<div …
=> Localization: embed in html, autorun, apply earlier

codemirror/.gitignore, codemirror/.travis.yml, codemirror/AUTHORS, codemirror/README.md, codemirror/addon/dialog/dialog.css, codemirror/addon/dialog/dialog.js, codemirror/addon/fold/foldgutter.js, codemirror/addon/hint/css-hint.js, codemirror/addon/hint/show-hint.js, codemirror/addon/lint/lint.js, codemirror/addon/scroll/annotatescrollbar.js, codemirror/addon/search/matchesonscrollbar.js, codemirror/addon/search/search.js, codemirror/addon/search/searchcursor.js, codemirror/bower.json, codemirror/index.html, codemirror/keymap/sublime.js, codemirror/keymap/vim.js, codemirror/lib/codemirror.css, codemirror/lib/codemirror.js, codemirror/mode/css/css.js, codemirror/mode/css/less.html, codemirror/mode/css/less_test.js, codemirror/mode/css/scss.html, codemirror/mode/css/scss_test.js, codemirror/package.json, codemirror/theme/liquibyte.css, codemirror/theme/mdn-like.css, codemirror/theme/monokai.css, codemirror/theme/solarized.css
* keep our custom css-lint.js, no changes in upstream
* use [newer show-hint.js](https://github.com/codemirror/CodeMirror/commit/bb61349fa659f29877b29e0ed7e2c4beea57ffe2) - {completeSingle: true} was broken in 5.2.0
* use [newer search.js](https://github.com/codemirror/CodeMirror/commit/a5f2de453f517c4fa88eccf92b8f010770278cf7) - replace() didn't use previous search query in 5.2.0
=> CodeMirror 5.2.1 update

_locales/en/messages.json, apply.js, background.js, edit.html, edit.js, health.js, manage.js, storage.js
Uses [getPackageDirectoryEntry](https://developer.chrome.com/extensions/runtime#method-getPackageDirectoryEntry) to populate the list of available CSS themes.
Currently Stylish is shipped with 34 themes in addition to a built-in "default": 3024-day, 3024-night, ambiance, ambiance-mobile, base16-dark, base16-light, blackboard, cobalt, colorforth, eclipse, elegant, erlang-dark, lesser-dark, liquibyte, mbo, mdn-like, midnight, monokai, neat, neo, night, paraiso-dark, paraiso-light, pastel-on-dark, rubyblue, solarized, the-matrix, tomorrow-night-bright, tomorrow-night-eighties, twilight, vibrant-ink, xq-dark, xq-light, zenburn.
A non-elegant timer-based CodeMirror refresh is used because some themes (rubyblue and a few others) have a small issue immediately upon selection: part of the gutter …
=> Editor: option to select CodeMirror CSS theme

edit.html, edit.js
Depends on #108 in `remove scroll-hack and hint-hack, not needed with CM5.2.1` commit.
FIXED:
* fix inconsistent behavior of browser hotkeys (F3, Shift-F3, Ctrl-S/F/G and so on) when they [should] do totally different things in the active keymap.
* fix jumpToLine overriding Ctrl-G in the active keymap, now Ctrl-J is assigned in such cases.
* fix "pcDefault" keymap when running on Windows by adding F3 and Shift-F3 - this keymap should mimick the browser.
* fix non-interceptable Ctrl-(Shift-)N/T/W in all keymaps on Windows.
* fix Alt-PgDn and Alt-PgUp (next/prev section) to work in applies-to inputs.
* fix autocomplete to use correct hotkey depending on active keymap.
* add "vim" keymap.
* add "emacs" keymap.
* workaround for Chrome bug (apparently [this …
=> Editor fixes

codemirror/addon/lint/css-lint.js, csslint/csslint.js
Closes #109.
Doesn't add `initial` keyword, though.
* CSSLint parser: 
* **0.2.5**/2015 (was 0.2.3/2013)
* +updates since 0.2.5 up to CSSLint/parser-lib@b6a2cbb
* +PR1: Add all SVG properties - mattiacci/parser-lib@59bbfc5
* +PR2: support for 'vertical-align: inherit' - mattiacci/parser-lib@52e3ad3
* CSSLint addon: warn on nonadjacent duplicate properties
=> CSSLint update

_locales/en/messages.json, codemirror/lib/codemirror.js, edit.js
* fix CodeMirror.normalizeKeyMap - the bug is [reported](https://github.com/codemirror/CodeMirror/issues/3258) and fixed upstream.
* pressing a hotkey in the first inputbox will filter the list by this hotkey
* ~~double Esc closes the popup~~
* ~~double Tab switches to next input~~
* ~~double Delete and double Backspace clear the input~~
* add localizable placeholders to inputboxes
* set initial focus to the command inputbox
=> Editor keymap help: press a hotkey to filter the list

edit.js
Don't assign hardcoded hotkeys for jumpToLine, autocomplete, findNext, findPrev if these are used in localStorage::`editor.options.extraKeys` user option.
=> Respect localStorage::editor.extraKeys user option

apply.js
On huge pages with lots of elements I see a 10x ([here](https://github.com/RequestPolicy/requestpolicy/compare/dev-1.0...RequestPolicyContinued:dev-1.0)) - 223x (private site) speedup: ~25% vs ~2% and ~0.12% combined CPU usage respectively.
This is expected, of course, because currently iframe observer is doing a lot of unneeded work on every mutation and large complex pages may produce thousands of calls while loading.
1. querySelectorAll was always known to be [extremely slow](http://jsperf.com/queryselectorall-vs-getelementbyid/35) (~140x slower than getElementById even now, huh?) and it was executed on \*every* call, now a global `g_styleElements` hash is used instead.
2. forEach, filter, map with function calls on thousands of nodes are slow by design, now `for` is used.<br>BTW, …
=> Make iframe observer 10-100 times faster

edit.js, storage.js
* Correctly determine when to save the window size on tab close
Previously the window size was overwritten with wrong values in case the only tab in Chrome window was the Manage styles page and then the Edit style page was opened by clicking some style's Edit button.
P.S. The PR has a generic name in case it will be stalled for a month and I'll find another bug to fix :D
=> Editor: fixes

edit.js, manage.html, manage.js
* initialize styles earlier (ask for styles before BODY is loaded)
* remember scroll position - resolves an extremely annoying issue when going back from an `Edit style` page that was invoked from the `Manage styles` page in case all the installed styles won't fit on one page, the latter being scrolled down.
P.S. `useCapture=false` parameter was deliberately removed from `addEventListener` as it's optional in Chrome [ever since v1.0](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility) in 2008.
=> Manage: remember scroll position, initialize styles earlier

_locales/en/messages.json, edit.html, edit.js
* An auto-updated list of CSSLint warnings and errors helps a lot in case the errors occur outside of the visible portion of the code (after text replace/paste operation, for example, or in case you simply haven't noticed the icon, which only appears after 0.5s by default, and scrolled the code).
* The entire CSSLint block is hidden when there is nothing to display.
* Click on a message to go to the source.<br>The hovered line is highlighted and uses a hand-shaped cursor, which should suggest it's clickable.
<sup>I heard you like global functions so I added global functions calling global functions while calling global functions.</sup>
=> Editor: show a list of all CSSLint messages

_locales/en/messages.json, beautify/beautify-css.js, edit.html, edit.js, storage.js
* [beautify-css](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-css.js) script with a few extra options is used, the original is in a separate commit to re-apply the extra options with more ease in case the external script is updated.
* global `Beautify` button and section beautify buttons are shown<br>(or maybe it's better to use `{}` label with `Beautify` tooltip for the sections?)
* options block appears after the Beautify button is pressed, its layout is dynamically changed in accordance with the selected space/newline separator between tokens, the code is automatically beautified using the new options.
* the script is only loaded when the button is pressed because it's not needed constantly like csslint, for example. I find it reasonable to apply the same …
=> Editor: CSS-beautifier

edit.js
HTML wasn't escaped in the CSSLint report, instead it was parsed and rendered as HTML.
Test case:
```css
a {
background-image: url("data:image/svg+xml !important;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' > <polygon points='0,0 50,100 100,0' fill='#888' stroke='#000' stroke-width='1' /> </svg>");
}
```
=> Editor: escape html in CSSLint report, limit message length

_locales/en/messages.json, csslint/csslint.js, edit.html, edit.js, storage.js
Closes #31
* CSSLint's [parser-lib](https://github.com/CSSLint/parser-lib) is used, with a few fixes ([PR for @keyframes](https://github.com/CSSLint/parser-lib/pull/157), nested doc handling is pending submission).
* `@-moz-document` and unprefixed `@document` are recognized
* The parser understands nested `@-moz-document` and puts a breaker `/*************/` between the parts of such divided outer sections
* Likewise, a global section is constructed from stuff outside of recognized sections
* If the global section only contains `@namespace url(http://www.w3.org/1999/xhtml);` and comments then it's not created.
A combined approach is used - parsing plus direct extraction of an entire section text in one go and a few regexps for detecting minor stuff. It seems failproof to me, moreover …
=> Editor: paste from Mozilla format

edit.js
A lot of (most?) applications disable the `Save` button when there are no changes, so this PR adds such functionality.
=> Editor: disable "Save" button when content is unmodified

_locales/ar/messages.json, _locales/cs/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/es/messages.json, _locales/fi/messages.json, _locales/fr/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/nl/messages.json, _locales/pt_BR/messages.json, _locales/ru/messages.json, _locales/sv/messages.json, _locales/sv_SE/messages.json, _locales/te/messages.json, _locales/tr/messages.json, _locales/zh/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json
@JasonBarnabe, please fix `pull_locales.rb` to autoimport the placeholders from `en/messages.json`.
Here's a python script to propagate the placeholders and use tabs for indents:
```python
#! python2
import io, os, json, re
from collections import OrderedDict
with io.open('_locales/en/messages.json', 'r', encoding='utf-8') as f:
english_placeholders = [(k, v['placeholders']) for k,v in json.load(f).items()
if 'placeholders' in v]
for locale_name in os.listdir('_locales'):
if locale_name == 'en':
continue
loc_path = '_locales/' + locale_name + '/messages.json'
with io.open(loc_path, 'r+', encoding='utf-8') as f:
loc = json.load(f, object_pairs_hook=OrderedDict)
changed = 0
for msgId, placeholder in english_placeholders:
if msgId in loc and cmp(placeholder, loc[msgId].get('placeholders', …
```
=> Add placeholders to locale files

apply.js
`apply.js::applyStyles` is called multiple times during page load sequence but we only need to process DOMContentLoaded event once, so this PR <s>adds `document.DOMContentLoadedBound` flag which is local to our content script</s> uses a non-anonymous callback which prevents the duplicates from being registered. The existing behavior didn't cause any actual harm though, except for dumb redundant processing of iframe elements.
=> Bind only one DOMContentLoaded event

edit.js
* Make `.CodeMirror-active` class stick when a child search/jump minidialog is focused unlike the built-in `.CodeMirror-focused` class. 
Thus it'll be possible to use a custom CSS style with a recolored active code box that won't annoyingly flicker every time the search/jump-to-line dialog is invoked.
* Focus the minidialog when switching find/replace. 
Previously, when a search minidialog was displayed and we pressed a hotkey to switch to another kind of minidialog (search <-> replace), the focus wasn't correctly preserved.
=> Editor: sticky .CodeMirror-active class for code boxes

edit.html, edit.js
In narrow width mode (737px and less) the editor window is very small so we should conserve the space.
This PR autocollapses the lint report down to its title that contains now a total number of issues.
The entire report is shown only on mousehover.
Fixes https://forum.userstyles.org/discussion/48155/bug-ish-who-in-the-world-decided-that-this-layout-was-a-good-idea
=> Autohide lint report in narrow mode; show # of issues

background.html, background.js, edit.js, manage.js, manifest.json, messaging.js, popup.js, storage.js
Closes #156
All setting are saved in a single object under `"settings"` key. In the future there'll be other keys for the [edited] styles, something like `"style1"`, `"style2"`, ...
* `localStorage` isn't needed now, on the first run all values are migrated, the old values are renamed to `DEPRECATED: name`.
* As for manual editing of the settings, it can be done with [Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb) extension.
* On extension startup the settings are read from `storage.sync` into internal variable that will be used to access the values directly, which is of course faster than the synchronous and DOM-blocking `localStorage`. Necessary `prefChanged` messages are broadcast, helps in case something …
=> Sync prefs

edit.html, edit.js
This is a simple implementation without any visual feedback that the action is possible, kinda hoping that it's obvious because on a touchscreen everything can be touched to interact with and thus the functionality will be naturally discovered.
=> Narrow-width editor on touchscreens: toggle lint report via click

edit.js
Make `Editor->import` preserve intermediary global sections instead of coalescing everything into one. The fix is needed as per [this discussion](https://forum.userstyles.org/discussion/comment/101413/#Comment_101413):
>Rule order is an element in the cascade, a determinant of which rule will set the property value. If you rearrange the rules you can change the calculated style.
>```css
DIV {color: magenta}
@-moz-document domain(userstyles.org) { DIV {color: cyan} }
DIV {color: yellow}
```
>is not the same as
>```css
DIV {color: magenta}
DIV {color: yellow}
@-moz-document domain(userstyles.org) { DIV {color: cyan} }
```
=> Import style globalsection fix
