- edit.html
Fixes #28
It's not perfect, but it should work well. Suggestions welcome.
> Added responsive design for editor

- manage.html
Pretty much the same thing as the edit page.
> Responsive design for Installed styles

- popup.html
Append the new menu entry to the existing entries for continuity with the previous menu layout.
Was https://github.com/JasonBarnabe/stylish-chrome/pull/32
> Make 'New style' the last menu action

- codemirror/addon/hint/css-hint.js
- codemirror/addon/hint/show-hint.css
- codemirror/addon/hint/show-hint.js
- edit.html
- edit.js
Two hint functions are used:
* **css-hint**.js: shows autocomplete hints for CSS properties _inside_ a { } rule definition
* **anyword-hint**.js: works _outside_ { } and uses all words in the code textarea - useful for classes, ids, etc.
> Edit style: autocomplete on Ctrl-Space using CodeMirror hint addon

- edit.js
Currently Stylish is oblivious of modified and unsaved code when closing the editor.
~~An obvious solution would be to use CodeMirror's "change" event notification, but it seems useless in case all changes where undone via Ctrl-Z. That's why a straightforward comparison of text was used in the code.~~ CodeMirror's changeGeneration / isClean are used thanks to @hideheader.
Modified code boxes are marked with `*` in their label.
> Edit style: warn before losing changes in code areas

- edit.html
- edit.js
Toggle a class on the container instead of changing label text.
> Fix 'dirty' indicator on 'Code' boxes

- _locales/en/messages.json
- background.js
- edit.html
- edit.js
- manage.html
- manage.js
- popup.js
* **Editor: don't scroll sections into view on click**, see #71
* **Manager: "Apply all updates" button** closes #36
How it works:
1. *checkUpdateAll* hooks checkUpdate with a callback that counts styles that have an update, during the process the button is disabled and turns gray
2. When the last style is checked, the button is re-enabled and *applyUpdateAll* button is displayed if there were styles with updates, its title also shows the number of updates
3. When *applyUpdateAll* is clicked it's immediately disabled&grayed, disappears after 1 second
> Editor tweaks 2

- edit.html
- edit.js
* With standard Chrome scrollbars
* Without scrollbars or with the upcoming overlay scrollbars via chrome://flags/#overlay-scrollbars
> Editor: add resize grip

- storage.js
> Ignore port number in url domain

- apply.js
- background.js
- edit.js
- messaging.js
- popup.js
- storage.js
> Apply styles to popup on change/disableAll

- _locales/ar/messages.json
- _locales/cs/messages.json
- _locales/de/messages.json
- _locales/el/messages.json
- _locales/es/messages.json
- _locales/fi/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/ja/messages.json
- _locales/nl/messages.json
- _locales/pt_BR/messages.json
- _locales/ru/messages.json
- _locales/sv/messages.json
- _locales/sv_SE/messages.json
- _locales/te/messages.json
- _locales/tr/messages.json
- _locales/zh/messages.json
- _locales/zh_CN/messages.json
- _locales/zh_TW/messages.json
- background.js
- edit.js
@JasonBarnabe, apparently `pull_locales.rb` should be updated to add the variable placeholders automatically, but I don't know Ruby.
> Bugfix for 1.3.0 release

- _locales/en/messages.json
- manage.html
- manage.js
Show only styles that have the entered text in their name or code or applies-to values.
> Manage styles: add search contents filter

- popup.js
* Fixes for Popup regressions
* autoclose after click on 'Edit' link
* ~~new option: Compact layout~~ - will be a separate PR
> Popup fixes

- edit.html
- edit.js
Closes #89.
* Full width:
---
* Narrow width
> Editor: add a link to the install source page

- edit.js
Partially alleviates #1.
* Codeboxes are auto sized to contents on start but only when all of them would fit on one page.
* Maximum height == `window.innerHeight`, otherwise CodeMirror/browser lags a lot.
* Minimum height is calculated from css (currently 300px defined in codemirror.css)
P.S. This time I've split the new features into several mini-PRs as requested, but it seems counter-productive to me because I'll have to resolve conflicts in each PR after the previous one is merged (they all alter edit.js).
> Editor: maximize height of code boxes when possible

- codemirror/addon/comment/comment.js
- codemirror/addon/selection/active-line.js
- edit.html
- edit.js
* highlight active line (the div is stylable)
* add toggle/line/block comment commands.<br>However `lineComment` isn't exposed as `//` isn't really a comment in CSS.
> Editor: highlight active line, add toggle/line/block comment commands

- edit.js
- storage.js
> Editor: set OS-dependent default keymap consistently

- edit.js
> Editor: show an empty code box for styles with no sections

- apply.js
Simply postpone removal of the old style element until the updated one is applied. Especially useful when editing a dark theme and frequently hitting Ctrl-S to "live-preview" the changes. I've also seen pages flicker occasionally when `webNavigation.onHistoryStateUpdated` handler was firing `styleReplaceAll` event.
> Avoid flicker when updating applied styles

- background.js
- manifest.json
- popup.js
`ftp://` scheme is mentioned in the [docs](https://developer.chrome.com/extensions/match_patterns) too.
> Support ftp urls

- background.js
Closes #162
`chrome.tabs.onUpdated` is used to catch direct URL hash modifications not invoked via HTML5 history API. At least two sites use that: office.com and mega.nz
test.html:
```html
<html>
<body>
<button onclick="location.hash=location.hash ? '' : 'test'">Test</button>
</body>
</html>
```
Style (edit the url prefix accordingly):
```css
@-moz-document url-prefix("file:///C:/test.html#test") {
body {background-color:blue}
}
```
> Apply styles upon direct URL hash modification

- manage.js
https://forum.userstyles.org/discussion/49688/chrome-my-userstyle-wont-get-updated
https://github.com/JasonBarnabe/stylish-chrome/issues/172
This is sufficient to make updates work again, but there are underlying problems.
> Updating from Style Manager failure
